all: optellen printarray max roteer
optellen: optellen.cpp
	g++ -c optellen.cpp
	g++ -o optellen optellen.o
	
printarray: printarray.cpp
	g++ -c printarray.cpp
	g++ -o printarray printarray.o
	
max: max.cpp
	g++ -c max.cpp
	g++ -o max max.o
	
roteer: roteer.cpp
	g++ -c roteer.cpp
	g++ -o roteer roteer.o