all: optellen printarray max roteer
optellen: optellen.cpp
	g++ -std=c++11 -c optellen.cpp
	g++ -o optellen optellen.o
	
printarray: printarray.cpp
	g++ -std=c++11 -c printarray.cpp
	g++ -o printarray printarray.o
	
max: max.cpp
	g++ -std=c++11 -c max.cpp
	g++ -o max max.o
	
roteer: roteer.cpp
	g++ -std=c++11 -c roteer.cpp
	g++ -o roteer roteer.o
