#! /bin/bash
#lame --decode mp3tje.mp3 | sox - nummer%1n.wav trim 0 30 : newfile : trim 30 60


if [ $# -lt 3 ]; then
  echo "$0: Usage: slicer filename numslices extension"
else
	numslices=$2
	numsamples=`soxi -s "$1"`

	slicelength=`bc <<< "$numsamples / $numslices"`

	dir=`dirname "$1"`

	while [ $numslices -gt 0 ]
	do
	  let numslices=numslices-1
	  let startsamp=numslices*$slicelength
		echo "Converting number $numslices to $dir/nummer$numslices.$3"
		sox "$1" "$dir/nummer$numslices.$3" trim $startsamp"s" $slicelength"s"

	done

  
fi
